import re

def insert_keys(lang_name, keys_str, content):
    pattern = rf"('{lang_name}':\s*{{)"
    replacement = rf"\1\n{keys_str}"
    return re.sub(pattern, replacement, content)

english = """
      'offer_new_skill': 'Offer New Skill',
      'title_label': 'Title',
      'title_hint': 'e.g. Web Engineering',
      'title_required': 'Title is required',
      'category_label': 'Category',
      'category_hint': 'Select a category',
      'category_required': 'Please select a category',
      'experience_level_label': 'Experience level',
      'experience_level_hint': 'Your experience level',
      'experience_level_required': 'Please select a level',
      'looking_for_label': "I\\'m looking for",
      'looking_for_hint': 'Exchange skill preferences',
      'looking_for_required': 'Please enter what you want',
      'portfolio_label': 'Portfolio',
      'portfolio_hint': 'Paste a link or tap to upload a doc',
      'portfolio_required': 'Portfolio link or document is required',
      'description_label': 'Description',
      'description_hint': 'Describe your skill, experience level and what you can offer…',
      'upload_tooltip': 'Upload portfolio doc',
      'uploading': 'Uploading…',
      'uploaded': 'Uploaded ✓',
      'file_uploaded': 'File uploaded successfully ✓',
      'upload_failed': 'Upload failed',
      'add_skill_btn': 'Add Skill',
      'my_swaps_title': 'My Swaps',
      'my_learning': 'My Learning',
      'my_teaching': 'My Teaching',"""

spanish = """
      'offer_new_skill': 'Ofrecer Nueva Habilidad',
      'title_label': 'Título',
      'title_hint': 'ej. Ingeniería Web',
      'title_required': 'El título es requerido',
      'category_label': 'Categoría',
      'category_hint': 'Selecciona una categoría',
      'category_required': 'Por favor selecciona una categoría',
      'experience_level_label': 'Nivel de experiencia',
      'experience_level_hint': 'Tu nivel de experiencia',
      'experience_level_required': 'Por favor selecciona un nível',
      'looking_for_label': "Estoy buscando",
      'looking_for_hint': 'Preferencias de habilidades de intercambio',
      'looking_for_required': 'Por favor ingresa lo que buscas',
      'portfolio_label': 'Portafolio',
      'portfolio_hint': 'Pega un enlace o toca para subir un documento',
      'portfolio_required': 'El enlace del portafolio o documento es requerido',
      'description_label': 'Descripción',
      'description_hint': 'Describe tu habilidad, nivel de experiencia y lo que puedes ofrecer…',
      'upload_tooltip': 'Subir documento de portafolio',
      'uploading': 'Subiendo…',
      'uploaded': 'Subido ✓',
      'file_uploaded': 'Archivo subido con éxito ✓',
      'upload_failed': 'Fallo al subir',
      'add_skill_btn': 'Añadir Habilidad',
      'my_swaps_title': 'Mis Intercambios',
      'my_learning': 'Mi Aprendizaje',
      'my_teaching': 'Mi Enseñanza',"""

french = """
      'offer_new_skill': 'Offrir une Nouvelle Compétence',
      'title_label': 'Titre',
      'title_hint': 'ex. Ingénierie Web',
      'title_required': 'Le titre est requis',
      'category_label': 'Catégorie',
      'category_hint': 'Sélectionnez une catégorie',
      'category_required': 'Veuillez sélectionner une catégorie',
      'experience_level_label': "Niveau d\\'expérience",
      'experience_level_hint': "Votre niveau d\\'expérience",
      'experience_level_required': 'Veuillez sélectionner un niveau',
      'looking_for_label': "Je cherche",
      'looking_for_hint': "Préférences de compétences d\\'échange",
      'looking_for_required': 'Veuillez entrer ce que vous voulez',
      'portfolio_label': 'Portfolio',
      'portfolio_hint': 'Collez un lien ou appuyez pour télécharger un doc',
      'portfolio_required': 'Le lien du portfolio ou le document est requis',
      'description_label': 'Description',
      'description_hint': 'Décrivez votre compétence, votre niveau d\\'expérience et ce que vous pouvez offrir…',
      'upload_tooltip': 'Télécharger le doc du portfolio',
      'uploading': 'Téléchargement…',
      'uploaded': 'Téléchargé ✓',
      'file_uploaded': 'Fichier téléchargé avec succès ✓',
      'upload_failed': 'Échec du téléchargement',
      'add_skill_btn': 'Ajouter Compétence',
      'my_swaps_title': 'Mes Échanges',
      'my_learning': 'Mon Apprentissage',
      'my_teaching': 'Mon Enseignement',"""

german = """
      'offer_new_skill': 'Neue Fähigkeit anbieten',
      'title_label': 'Titel',
      'title_hint': 'z.B. Web-Engineering',
      'title_required': 'Titel ist erforderlich',
      'category_label': 'Kategorie',
      'category_hint': 'Wählen Sie eine Kategorie',
      'category_required': 'Bitte wählen Sie eine Kategorie',
      'experience_level_label': 'Erfahrungsstufe',
      'experience_level_hint': 'Ihre Erfahrungsstufe',
      'experience_level_required': 'Bitte wählen Sie eine Stufe',
      'looking_for_label': "Ich suche",
      'looking_for_hint': 'Austauschfähigkeiten Präferenzen',
      'looking_for_required': 'Bitte geben Sie ein, was Sie möchten',
      'portfolio_label': 'Portfolio',
      'portfolio_hint': 'Fügen Sie einen Link ein oder tippen Sie, um ein Dokument hochzuladen',
      'portfolio_required': 'Portfolio-Link oder Dokument ist erforderlich',
      'description_label': 'Beschreibung',
      'description_hint': 'Beschreiben Sie Ihre Fähigkeit, Erfahrungsstufe und was Sie anbieten können…',
      'upload_tooltip': 'Portfolio-Dokument hochladen',
      'uploading': 'Wird hochgeladen…',
      'uploaded': 'Hochgeladen ✓',
      'file_uploaded': 'Datei erfolgreich hochgeladen ✓',
      'upload_failed': 'Upload fehlgeschlagen',
      'add_skill_btn': 'Fähigkeit hinzufügen',
      'my_swaps_title': 'Meine Austausche',
      'my_learning': 'Mein Lernen',
      'my_teaching': 'Mein Unterrichten',"""

japanese = """
      'offer_new_skill': '新しいスキルを提供する',
      'title_label': 'タイトル',
      'title_hint': '例: ウェブエンジニアリング',
      'title_required': 'タイトルは必須です',
      'category_label': 'カテゴリー',
      'category_hint': 'カテゴリーを選択',
      'category_required': 'カテゴリーを選択してください',
      'experience_level_label': '経験レベル',
      'experience_level_hint': 'あなたの経験レベル',
      'experience_level_required': 'レベルを選択してください',
      'looking_for_label': "探しているもの",
      'looking_for_hint': '交換するスキルの希望',
      'looking_for_required': '希望を入力してください',
      'portfolio_label': 'ポートフォリオ',
      'portfolio_hint': 'リンクを貼り付けるかタップしてドキュメントをアップロード',
      'portfolio_required': 'ポートフォリオのリンクまたはドキュメントは必須です',
      'description_label': '説明',
      'description_hint': 'あなたのスキル、経験レベル、提供できることを説明してください…',
      'upload_tooltip': 'ポートフォリオドキュメントをアップロード',
      'uploading': 'アップロード中…',
      'uploaded': 'アップロード完了 ✓',
      'file_uploaded': 'ファイルのアップロードに成功しました ✓',
      'upload_failed': 'アップロードに失敗しました',
      'add_skill_btn': 'スキルを追加',
      'my_swaps_title': '私の交換',
      'my_learning': '私の学習',
      'my_teaching': '私の指導',"""

chinese = """
      'offer_new_skill': '提供新技能',
      'title_label': '标题',
      'title_hint': '例如：Web 工程',
      'title_required': '标题为必填项',
      'category_label': '类别',
      'category_hint': '选择一个类别',
      'category_required': '请选择一个类别',
      'experience_level_label': '经验水平',
      'experience_level_hint': '您的经验水平',
      'experience_level_required': '请选择一个水平',
      'looking_for_label': "我正在寻找",
      'looking_for_hint': '交换技能偏好',
      'looking_for_required': '请输入您想要的',
      'portfolio_label': '作品集',
      'portfolio_hint': '粘贴链接或点击上传文档',
      'portfolio_required': '作品集链接或文档为必填项',
      'description_label': '描述',
      'description_hint': '描述您的技能、经验水平以及您能提供的…',
      'upload_tooltip': '上传作品集文档',
      'uploading': '上传中…',
      'uploaded': '已上传 ✓',
      'file_uploaded': '文件上传成功 ✓',
      'upload_failed': '上传失败',
      'add_skill_btn': '添加技能',
      'my_swaps_title': '我的交换',
      'my_learning': '我的学习',
      'my_teaching': '我的教学',"""

arabic = """
      'offer_new_skill': 'تقديم مهارة جديدة',
      'title_label': 'العنوان',
      'title_hint': 'مثال: هندسة الويب',
      'title_required': 'العنوان مطلوب',
      'category_label': 'الفئة',
      'category_hint': 'اختر فئة',
      'category_required': 'الرجاء اختيار فئة',
      'experience_level_label': 'مستوى الخبرة',
      'experience_level_hint': 'مستوى خبرتك',
      'experience_level_required': 'الرجاء اختيار مستوى',
      'looking_for_label': "أنا أبحث عن",
      'looking_for_hint': 'تفضيلات مهارة التبادل',
      'looking_for_required': 'الرجاء إدخال ما تريد',
      'portfolio_label': 'محفظة الأعمال',
      'portfolio_hint': 'الصق رابطًا أو انقر لتحميل مستند',
      'portfolio_required': 'رابط المحفظة أو المستند مطلوب',
      'description_label': 'الوصف',
      'description_hint': 'صف مهارتك، مستوى خبرتك وما يمكنك تقديمه…',
      'upload_tooltip': 'تحميل مستند المحفظة',
      'uploading': 'جاري التحميل…',
      'uploaded': 'تم التحميل ✓',
      'file_uploaded': 'تم تحميل الملف بنجاح ✓',
      'upload_failed': 'فشل التحميل',
      'add_skill_btn': 'إضافة مهارة',
      'my_swaps_title': 'مبادلاتي',
      'my_learning': 'تَعَلُّمي',
      'my_teaching': 'تَدريسي',"""

russian = """
      'offer_new_skill': 'Предложить новый навык',
      'title_label': 'Заголовок',
      'title_hint': 'напр. Веб-разработка',
      'title_required': 'Заголовок обязателен',
      'category_label': 'Категория',
      'category_hint': 'Выберите категорию',
      'category_required': 'Пожалуйста, выберите категорию',
      'experience_level_label': 'Уровень опыта',
      'experience_level_hint': 'Ваш уровень опыта',
      'experience_level_required': 'Пожалуйста, выберите уровень',
      'looking_for_label': "Я ищу",
      'looking_for_hint': 'Предпочтения для обмена',
      'looking_for_required': 'Пожалуйста, введите то, что вы ищете',
      'portfolio_label': 'Портфолио',
      'portfolio_hint': 'Вставьте ссылку или нажмите, чтобы загрузить документ',
      'portfolio_required': 'Ссылка на портфолио или документ обязательны',
      'description_label': 'Описание',
      'description_hint': 'Опишите ваш навык, уровень опыта и что вы можете предложить…',
      'upload_tooltip': 'Загрузить документ портфолио',
      'uploading': 'Загрузка…',
      'uploaded': 'Загружено ✓',
      'file_uploaded': 'Файл успешно загружен ✓',
      'upload_failed': 'Ошибка загрузки',
      'add_skill_btn': 'Добавить навык',
      'my_swaps_title': 'Мои обмены',
      'my_learning': 'Мое обучение',
      'my_teaching': 'Мое преподавание',"""

portuguese = """
      'offer_new_skill': 'Oferecer Nova Habilidade',
      'title_label': 'Título',
      'title_hint': 'ex. Engenharia Web',
      'title_required': 'O título é obrigatório',
      'category_label': 'Categoria',
      'category_hint': 'Selecione uma categoria',
      'category_required': 'Por favor, selecione uma categoria',
      'experience_level_label': 'Nível de experiência',
      'experience_level_hint': 'Seu nível de experiência',
      'experience_level_required': 'Por favor, selecione um nível',
      'looking_for_label': "Estou procurando por",
      'looking_for_hint': 'Preferências de troca de habilidades',
      'looking_for_required': 'Por favor, insira o que você quer',
      'portfolio_label': 'Portfólio',
      'portfolio_hint': 'Cole um link ou toque para enviar um doc',
      'portfolio_required': 'O link do portfólio ou documento é obrigatório',
      'description_label': 'Descrição',
      'description_hint': 'Descreva sua habilidade, nível de experiência e o que você pode oferecer…',
      'upload_tooltip': 'Enviar doc do portfólio',
      'uploading': 'Enviando…',
      'uploaded': 'Enviado ✓',
      'file_uploaded': 'Arquivo enviado com sucesso ✓',
      'upload_failed': 'Falha no envio',
      'add_skill_btn': 'Adicionar Habilidade',
      'my_swaps_title': 'Minhas Trocas',
      'my_learning': 'Meu Aprendizado',
      'my_teaching': 'Meu Ensino',"""

italian = """
      'offer_new_skill': 'Offri una Nuova Competenza',
      'title_label': 'Titolo',
      'title_hint': 'es. Ingegneria Web',
      'title_required': 'Il titolo è richiesto',
      'category_label': 'Categoria',
      'category_hint': 'Seleziona una categoria',
      'category_required': 'Si prega di selezionare una categoria',
      'experience_level_label': 'Livello di esperienza',
      'experience_level_hint': 'Il tuo livello di esperienza',
      'experience_level_required': 'Si prega di selezionare un livello',
      'looking_for_label': "Sto cercando",
      'looking_for_hint': 'Preferenze di scambio competenze',
      'looking_for_required': 'Si prega di inserire cosa si desidera',
      'portfolio_label': 'Portfolio',
      'portfolio_hint': 'Incolla un link o tocca per caricare un doc',
      'portfolio_required': 'Link al portfolio o documento è richiesto',
      'description_label': 'Descrizione',
      'description_hint': 'Descrivi la tua competenza, livello di esperienza e cosa puoi offrire…',
      'upload_tooltip': 'Carica documento portfolio',
      'uploading': 'Caricamento…',
      'uploaded': 'Caricato ✓',
      'file_uploaded': 'File caricato con successo ✓',
      'upload_failed': 'Caricamento fallito',
      'add_skill_btn': 'Aggiungi Competenza',
      'my_swaps_title': 'I Miei Scambi',
      'my_learning': 'Il Mio Apprendimento',
      'my_teaching': 'Il Mio Insegnamento',"""

urdu = """
      'offer_new_skill': 'نئی مہارت پیش کریں',
      'title_label': 'عنوان',
      'title_hint': 'مثال: ویب انجینئرنگ',
      'title_required': 'عنوان درکار ہے',
      'category_label': 'زمرہ',
      'category_hint': 'ایک زمرہ منتخب کریں',
      'category_required': 'براہ کرم ایک زمرہ منتخب کریں',
      'experience_level_label': 'تجربے کی سطح',
      'experience_level_hint': 'آپ کے تجربے کی سطح',
      'experience_level_required': 'براہ کرم ایک سطح منتخب کریں',
      'looking_for_label': "میں تلاش کر رہا ہوں",
      'looking_for_hint': 'تبادلہ کی مہارت کی ترجیحات',
      'looking_for_required': 'براہ کرم درج کریں جو آپ چاہتے ہیں',
      'portfolio_label': 'پورٹ فولیو',
      'portfolio_hint': 'ایک لنک چسپاں کریں یا دستاویز اپ لوڈ کرنے کے لیے تھپتھپائیں',
      'portfolio_required': 'پورٹ فولیو کا لنک یا دستاویز درکار ہے',
      'description_label': 'تفصیل',
      'description_hint': 'اپنی مہارت، تجربے کی سطح اور جو آپ پیش کر سکتے ہیں اس کی وضاحت کریں…',
      'upload_tooltip': 'پورٹ فولیو کی دستاویز اپ لوڈ کریں',
      'uploading': 'اپ لوڈ ہو رہا ہے…',
      'uploaded': 'اپ لوڈ ہو گیا ✓',
      'file_uploaded': 'فائل کامیابی سے اپ لوڈ ہو گئی ✓',
      'upload_failed': 'اپ لوڈ ناکام ہو گیا',
      'add_skill_btn': 'مہارت شامل کریں',
      'my_swaps_title': 'میرے تبادلے',
      'my_learning': 'میری تعلیم',
      'my_teaching': 'میری تدریس',"""

hindi = """
      'offer_new_skill': 'नया कौशल प्रदान करें',
      'title_label': 'शीर्षक',
      'title_hint': 'उदा. वेब इंजीनियरिंग',
      'title_required': 'शीर्षक आवश्यक है',
      'category_label': 'श्रेणी',
      'category_hint': 'एक श्रेणी चुनें',
      'category_required': 'कृपया एक श्रेणी चुनें',
      'experience_level_label': 'अनुभव स्तर',
      'experience_level_hint': 'आपका अनुभव स्तर',
      'experience_level_required': 'कृपया एक स्तर चुनें',
      'looking_for_label': "मैं ढूंढ रहा हूँ",
      'looking_for_hint': 'कौशल वरीयताओं का आदान-प्रदान करें',
      'looking_for_required': 'कृपया दर्ज करें कि आप क्या चाहते हैं',
      'portfolio_label': 'पोर्टफोलियो',
      'portfolio_hint': 'एक लिंक पेस्ट करें या दस्तावेज़ अपलोड करने के लिए टैप करें',
      'portfolio_required': 'पोर्टफोलियो लिंक या दस्तावेज़ आवश्यक है',
      'description_label': 'विवरण',
      'description_hint': 'अपने कौशल, अनुभव स्तर और आप क्या पेशकश कर सकते हैं, इसका वर्णन करें…',
      'upload_tooltip': 'पोर्टफोलियो दस्तावेज़ अपलोड करें',
      'uploading': 'अपलोड हो रहा है…',
      'uploaded': 'अपलोड हो गया ✓',
      'file_uploaded': 'फ़ाइल सफलतापूर्वक अपलोड हो गई ✓',
      'upload_failed': 'अपलोड विफल रहा',
      'add_skill_btn': 'कौशल जोड़ें',
      'my_swaps_title': 'मेरे आदान-प्रदान',
      'my_learning': 'मेरी शिक्षा',
      'my_teaching': 'मेरा शिक्षण',"""

import os
filepath = r'd:\skill-swap\lib\Ui_helper\translation_helper.dart'
with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

content = insert_keys('en', english, content)
content = insert_keys('es', spanish, content)
content = insert_keys('fr', french, content)
content = insert_keys('de', german, content)
content = insert_keys('ja', japanese, content)
content = insert_keys('zh', chinese, content)
content = insert_keys('ar', arabic, content)
content = insert_keys('ru', russian, content)
content = insert_keys('pt', portuguese, content)
content = insert_keys('it', italian, content)
content = insert_keys('ur', urdu, content)
content = insert_keys('hi', hindi, content)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)
print("Keys added to translation_helper.dart")
