// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXNiFNh7eX7WiTOwI-Q7HIu583iexsMRM',
    appId: '1:842620144803:web:cc39e798add26ec0780316',
    messagingSenderId: '842620144803',
    projectId: 'skill-swapx-ac361',
    authDomain: 'skill-swapx-ac361.firebaseapp.com',
    storageBucket: 'skill-swapx-ac361.firebasestorage.app',
    measurementId: 'G-4WM3S3DR9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATvAr1oBGDyeWhe3XszOOZbFi2N5jDG7Y',
    appId: '1:842620144803:android:01a942428fcb7780780316',
    messagingSenderId: '842620144803',
    projectId: 'skill-swapx-ac361',
    storageBucket: 'skill-swapx-ac361.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2nXHit-9LrO-Sqik1_-qLoc6nNIxTDZk',
    appId: '1:842620144803:ios:fbd748f717286124780316',
    messagingSenderId: '842620144803',
    projectId: 'skill-swapx-ac361',
    storageBucket: 'skill-swapx-ac361.firebasestorage.app',
    iosBundleId: 'com.example.skillSwap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2nXHit-9LrO-Sqik1_-qLoc6nNIxTDZk',
    appId: '1:842620144803:ios:fbd748f717286124780316',
    messagingSenderId: '842620144803',
    projectId: 'skill-swapx-ac361',
    storageBucket: 'skill-swapx-ac361.firebasestorage.app',
    iosBundleId: 'com.example.skillSwap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXNiFNh7eX7WiTOwI-Q7HIu583iexsMRM',
    appId: '1:842620144803:web:c2039f186205930c780316',
    messagingSenderId: '842620144803',
    projectId: 'skill-swapx-ac361',
    authDomain: 'skill-swapx-ac361.firebaseapp.com',
    storageBucket: 'skill-swapx-ac361.firebasestorage.app',
    measurementId: 'G-6H95YLF8KH',
  );
}
